{{- if .Values.orchestrator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.akvorado-orchestrator-metrics.entrypoints: private
    traefik.http.routers.akvorado-orchestrator-metrics.observability.accesslogs: "false"
    traefik.http.routers.akvorado-orchestrator-metrics.rule: PathPrefix(`/api/v0/orchestrator/metrics`)
    traefik.http.routers.akvorado-orchestrator-metrics.service: akvorado-orchestrator
    traefik.http.routers.akvorado-orchestrator.entrypoints: private
    traefik.http.routers.akvorado-orchestrator.rule: PathPrefix(`/api/v0/orchestrator`)
    traefik.http.services.akvorado-orchestrator.loadbalancer.server.port: "8080"
  labels:
    {{- include "akvorado.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
  name: {{ include "akvorado.orchestrator.fullname" . }}
spec:
  replicas: {{ .Values.orchestrator.replicaCount }}
  selector:
    matchLabels:
      {{- include "akvorado.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: orchestrator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
        traefik.enable: "true"
        traefik.http.routers.akvorado-orchestrator-metrics.entrypoints: private
        traefik.http.routers.akvorado-orchestrator-metrics.observability.accesslogs: "false"
        traefik.http.routers.akvorado-orchestrator-metrics.rule: PathPrefix(`/api/v0/orchestrator/metrics`)
        traefik.http.routers.akvorado-orchestrator-metrics.service: akvorado-orchestrator
        traefik.http.routers.akvorado-orchestrator.entrypoints: private
        traefik.http.routers.akvorado-orchestrator.rule: PathPrefix(`/api/v0/orchestrator`)
        traefik.http.services.akvorado-orchestrator.loadbalancer.server.port: "8080"
      labels:
        {{- include "akvorado.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: orchestrator
    spec:
      containers:
        - name: {{ include "akvorado.orchestrator.name" . }}
          args:
            - orchestrator
            - /etc/akvorado/akvorado.yaml
          image: "{{ .Values.orchestrator.image.repository }}:{{ .Values.orchestrator.image.tag }}"
          imagePullPolicy: {{ .Values.orchestrator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.orchestrator.containerPorts.http }}
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/akvorado
              name: akvorado-orchestrator-claim0
              readOnly: true
            - mountPath: /usr/share/GeoIP
              name: akvorado-geoip
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: akvorado-orchestrator-claim0
          persistentVolumeClaim:
            claimName: {{ include "akvorado.orchestrator.fullname" . }}
            readOnly: true
        - name: akvorado-geoip
          persistentVolumeClaim:
            claimName: akvorado-geoip
            readOnly: true
{{- end }}
