{{- if .Values.inlet.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "akvorado.inlet.fullname" . }}
  labels:
    {{- include "akvorado.labels" . | nindent 4 }}
  {{- with .Values.inlet.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.inlet.service.type }}
  {{- if .Values.inlet.service.clusterIP }}
  clusterIP: {{ .Values.inlet.service.clusterIP }}
  {{- end }}
  {{- if .Values.inlet.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.inlet.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.inlet.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.inlet.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if .Values.inlet.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.inlet.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.inlet.service.sessionAffinity }}
  sessionAffinity: {{ .Values.inlet.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.inlet.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- toYaml .Values.inlet.service.sessionAffinityConfig | nindent 4 }}
  {{- end }}
  ports:
    - name: netflow
      port: {{ .Values.inlet.service.ports.netflow }}
      protocol: UDP
      targetPort: netflow
      {{- if .Values.inlet.service.nodePorts.netflow }}
      nodePort: {{ .Values.inlet.service.nodePorts.netflow }}
      {{- end }}
    - name: sflow
      port: {{ .Values.inlet.service.ports.sflow }}
      protocol: UDP
      targetPort: sflow
      {{- if .Values.inlet.service.nodePorts.sflow }}
      nodePort: {{ .Values.inlet.service.nodePorts.sflow }}
      {{- end }}
    - name: http
      port: {{ .Values.inlet.service.ports.http }}
      targetPort: http
      protocol: TCP
      {{- if .Values.inlet.service.nodePorts.http }}
      nodePort: {{ .Values.inlet.service.nodePorts.http }}
      {{- end }}
  {{- if .Values.inlet.service.extraPorts }}
    {{- toYaml .Values.inlet.service.extraPorts | nindent 4 }}
  {{- end }}
  selector:
    {{- include "akvorado.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: inlet
{{- end }}
