apiVersion: v1
kind: Service
metadata:
  annotations:
    akvorado.conntrack.fix: "true"
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.akvorado-inlet-metrics.entrypoints: private
    traefik.http.routers.akvorado-inlet-metrics.observability.accesslogs: "false"
    traefik.http.routers.akvorado-inlet-metrics.rule: PathPrefix(`/api/v0/inlet/metrics`)
    traefik.http.routers.akvorado-inlet-metrics.service: akvorado-inlet
    traefik.http.routers.akvorado-inlet.entrypoints: private
    traefik.http.routers.akvorado-inlet.rule: PathPrefix(`/api/v0/inlet`)
    traefik.http.services.akvorado-inlet.loadbalancer.server.port: "8080"
  labels:
    io.kompose.service: akvorado-inlet
  name: akvorado-inlet
spec:
  ports:
    - name: "2055"
      port: 2055
      protocol: UDP
      targetPort: 2055
    - name: "6343"
      port: 6343
      protocol: UDP
      targetPort: 6343
    - name: "10179"
      port: 10179
      targetPort: 10179
  selector:
    io.kompose.service: akvorado-inlet
