{{- if .Values.inlet.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    akvorado.conntrack.fix: "true"
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
    traefik.enable: "true"
    traefik.http.routers.akvorado-inlet-metrics.entrypoints: private
    traefik.http.routers.akvorado-inlet-metrics.observability.accesslogs: "false"
    traefik.http.routers.akvorado-inlet-metrics.rule: PathPrefix(`/api/v0/inlet/metrics`)
    traefik.http.routers.akvorado-inlet-metrics.service: akvorado-inlet
    traefik.http.routers.akvorado-inlet.entrypoints: private
    traefik.http.routers.akvorado-inlet.rule: PathPrefix(`/api/v0/inlet`)
    traefik.http.services.akvorado-inlet.loadbalancer.server.port: "8080"
  labels:
    io.kompose.service: akvorado-inlet
  name: {{ include "akvorado.inlet.fullname" . }}
spec:
  replicas: {{ .Values.inlet.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: akvorado-inlet
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        akvorado.conntrack.fix: "true"
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
        traefik.enable: "true"
        traefik.http.routers.akvorado-inlet-metrics.entrypoints: private
        traefik.http.routers.akvorado-inlet-metrics.observability.accesslogs: "false"
        traefik.http.routers.akvorado-inlet-metrics.rule: PathPrefix(`/api/v0/inlet/metrics`)
        traefik.http.routers.akvorado-inlet-metrics.service: akvorado-inlet
        traefik.http.routers.akvorado-inlet.entrypoints: private
        traefik.http.routers.akvorado-inlet.rule: PathPrefix(`/api/v0/inlet`)
        traefik.http.services.akvorado-inlet.loadbalancer.server.port: "8080"
      labels:
        io.kompose.service: akvorado-inlet
    spec:
      containers:
        - name: {{ include "akvorado.inlet.name" . }}
          image: ghcr.io/akvorado/akvorado:main
          args:
            - inlet
            - http://akvorado-orchestrator:8080
          env:
            - name: AKVORADO_CFG_INLET_METADATA_CACHEPERSISTFILE
              value: /run/akvorado/metadata.cache
          ports:
            - name: netflow
              containerPort: {{ .Values.inlet.containerPorts.netflow }}
              protocol: UDP
            - name: sflow
              containerPort: {{ .Values.inlet.containerPorts.sflow }}
              protocol: UDP
            - name: http
              containerPort: {{ .Values.inlet.containerPorts.http }}
              protocol: TCP
          volumeMounts:
            - mountPath: {{ .Values.inlet.persistence.mountPath }}
              name: akvorado-run
      restartPolicy: Always
      volumes:
        - name: akvorado-run
          persistentVolumeClaim:
            claimName: {{ include "akvorado.inlet.fullname" . }}
{{- end }}
