apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: akvorado-console-db
  name: akvorado-console-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
