apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: akvorado-conntrack-fixer
  name: akvorado-conntrack-fixer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: akvorado-conntrack-fixer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: akvorado-conntrack-fixer
    spec:
      containers:
        - args:
            - conntrack-fixer
          image: ghcr.io/akvorado/akvorado:main
          name: akvorado-conntrack-fixer
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      restartPolicy: Always
