apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: akvorado-geoip
  name: akvorado-geoip
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
